import { Toaster } from "@/lib/toast";
import { ThemeRegistry } from "@/theme";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry>
          <Toaster durationMs={3000} maxVisibleToasts={4} isDismissible={false} />
          {children}
        </ThemeRegistry>
      </body>
    </html>
  );
}
